### ISSUE TITLE
Question about PCI

### ISSUE THREAD

**Issue by yacineMahdid** [renzocom/PCIst#1]
Hi there, do you have the original PCI code (not the PCIst) that was used in the Casali et al. (2013) paper?

**Comment by renzocom** [comment]
Hi Yacine, there is [this](https://github.com/noreun/pypci) python version of the original PCI. Note that you still have to calculate the significant sources (source modelling + statistics) to use as input to the function.

**Comment by yacineMahdid** [comment]
Great thanks!
